trigger:
  - master

pool:
  name: wsl

steps:

  ## TERRAFORM
  - script: terraform init --backend-config backend.tfvars
    displayName:  Terraform init
    workingDirectory: $(Build.SourcesDirectory)/terraform
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

  - script: terraform plan
    displayName:  Terraform plan
    workingDirectory: $(Build.SourcesDirectory)/terraform
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

  - script: terraform apply -auto-approve
    displayName:  Terraform apply
    workingDirectory: $(Build.SourcesDirectory)/terraform
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

  - script: |
      connection_string=$(terraform output -raw app_insights_connection_string)
      echo "##vso[task.setvariable variable=AZURE_MONITOR_CONNECTION_STRING;issecret=true]$connection_string"
    displayName: Get Azure Monitor connection string
    workingDirectory: $(Build.SourcesDirectory)/terraform

  - script: sudo apt-get install -y python3-venv
    displayName: Install python3-venv

  ## ANSIBLE
  - script: |
      python3 -m venv venv
      source venv/bin/activate
      pip install ansible[azure]
      pip install azure-mgmt-compute azure-mgmt-network azure-mgmt-resource
    displayName:  Get requirements

  - script: ansible-playbook playbookdemo.yml -i inv.azure_rm.yml
    displayName:  Ansible playbook
    workingDirectory: $(Build.SourcesDirectory)/ansible
    env:
      AZURE_CLIENT_ID: $(ARM_CLIENT_ID)
      AZURE_SECRET: $(ARM_SECRET)
      AZURE_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      AZURE_TENANT: $(ARM_TENANT)
      AZURE_MONITOR_CONNECTION_STRING: $(AZURE_MONITOR_CONNECTION_STRING)
      ANSIBLE_HOST_KEY_CHECKING: False