---
plugin: azure_rm

include_vm_resource_groups:
  - bookRg

auth_source: env
client_id: "{{ lookup('env','AZURE_CLIENT_ID') }}"
secret: "{{ lookup('env','AZURE_SECRET') }}"
tenant: "{{ lookup('env','AZURE_TENANT') }}"
subscription_id: "{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}"

keyed_groups:
 - key: tags.role