---
- hosts: _webserver
  become: true
  vars:
    - ansible_user: book
    - ansible_password: book123*
  tasks:
  - name: installing latest version of Nginx
    apt:
      name: nginx
      state: latest
  - name: start nginx service
    service:
      name: nginx
      state: started